spring.application.name=SpringSec
spring.security.user.name=rushikesh
spring.security.user.password=root



spring.datasource.url=jdbc:postgresql://localhost:9090/springsec_db
spring.datasource.username=rushi
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true